# -*- coding: utf-8 -*-
"""Lab3Chap7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1syGfxhwDoIirmBd86BobmR0hCxuB66ge
"""

def infix_to_postfix(infix: str) -> str:
    priority = {'+': 1, '-': 1, '*': 2}
    result = []
    temp = []

    for item in infix.split():
        if item.lstrip('-').isdigit():
            result.append(item)
        elif item == '(':
            temp.append(item)
        elif item == ')':
            while temp and temp[-1] != '(':
                result.append(temp.pop())
            temp.pop()  # Remove '('
        else:  # Operator
            while (temp and temp[-1] != '(' and
                   temp[-1] in priority and
                   priority[temp[-1]] >= priority[item]):
                result.append(temp.pop())
            temp.append(item)

    while temp:
        result.append(temp.pop())

    return ' '.join(result)


def infix_to_prefix(infix: str) -> str:
    priority = {'+': 1, '-': 1, '*': 2}
    reversed_tokens = infix.split()[::-1]

    # Swap parentheses
    fixed = []
    for item in reversed_tokens:
        if item == '(':
            fixed.append(')')
        elif item == ')':
            fixed.append('(')
        else:
            fixed.append(item)

    result = []
    temp = []

    for item in fixed:
        if item.lstrip('-').isdigit():
            result.append(item)
        elif item == '(':
            temp.append(item)
        elif item == ')':
            while temp and temp[-1] != '(':
                result.append(temp.pop())
            temp.pop()  # Remove '('
        else:  # Operator
            while (temp and temp[-1] != '(' and
                   temp[-1] in priority and
                   priority[temp[-1]] > priority[item]):
                result.append(temp.pop())
            temp.append(item)

    while temp:
        result.append(temp.pop())

    return ' '.join(result[::-1])


def evaluate_postfix(postfix: str) -> float:
    numbers = []

    for item in postfix.split():
        if item.lstrip('-').isdigit():
            numbers.append(float(item))
        else:
            second = numbers.pop()
            first = numbers.pop()
            if item == '+':
                numbers.append(first + second)
            elif item == '-':
                numbers.append(first - second)
            elif item == '*':
                numbers.append(first * second)

    return numbers[0]


def evaluate_prefix(prefix: str) -> float:
    numbers = []
    reversed_tokens = prefix.split()[::-1]

    for item in reversed_tokens:
        if item.lstrip('-').isdigit():
            numbers.append(float(item))
        else:
            first = numbers.pop()
            second = numbers.pop()
            if item == '+':
                numbers.append(first + second)
            elif item == '-':
                numbers.append(first - second)
            elif item == '*':
                numbers.append(first * second)

    return numbers[0]


def main():
    infix = input("Enter infix expression: ")

    postfix = infix_to_postfix(infix)
    prefix = infix_to_prefix(infix)
    postfix_result = evaluate_postfix(postfix)
    prefix_result = evaluate_prefix(prefix)

    print(f"Postfix: {postfix}")
    print(f"Prefix: {prefix}")
    print(f"Postfix Evaluation: {postfix_result}")
    print(f"Prefix Evaluation: {prefix_result}")


if __name__ == "__main__":
    main()